name       : qodem
version    : 1.0.1
release    : 2
source     :
    - https://github.com/klamonte/qodem/archive/refs/tags/v1.0.1.tar.gz : 84aecd322839c615c6f465128ea3231163067606704f19ffa50e5d3481b6ff01
license    : GPL-3.0-or-later
component  : system.utils
summary    : Qodem Terminal Emulator
description: |
    Qodem is a from-scratch clone implementation of the Qmodem communications program made popular in the days when Bulletin Board Systems ruled the night.
builddeps  :
    - pkgconfig(miniupnpc)
    - pkgconfig(sdl)
    - gpm-devel
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
