name       : qodem
version    : 1.0.0
release    : 1
source     :
    - https://github.com/klamonte/qodem/archive/v1.0.0.tar.gz : 632c138d09ff419265902026392ea220c23901fc2593f6456f922d7062fad736
license    : GPL-3.0
component  : system.utils
summary    : Qodem Terminal Emulator
description: |
    Qodem is a from-scratch clone implementation of the Qmodem communications program made popular in the days when Bulletin Board Systems ruled the night.
builddeps  :
    - pkgconfig(sdl)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
