name       : qodem
version    : 1.0.1
release    : 3
source     :
    - http://downloads.sourceforge.net/project/qodem/qodem/1.0.1/qodem-1.0.1.tar.gz : dedc73bfa73ced5c6193f1baf1ffe91f7accaad55a749240db326cebb9323359
license    : GPL-3.0-or-later
component  : system.utils
summary    : Qodem Terminal Emulator
description: |
    Qodem is a from-scratch clone implementation of the Qmodem communications program made popular in the days when Bulletin Board Systems ruled the night.
builddeps  :
    - pkgconfig(miniupnpc)
    - pkgconfig(sdl)
    - gpm-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
